### ISSUE TITLE
标注图像领用记录

### ISSUE THREAD

**Issue by liudm1** [EmbryoAI/EmbryoAI-System#4]
请大家自己下载要标注的图像，并在此提交图像领用记录。
图像下载地址：http://39.104.173.18:9000/minio/test/annos/

**Comment by liudm1** [comment]
已下载 20180418160200.tar.gz

**Comment by a3225167** [comment]
已领取 20180417153700.tar.gz

**Comment by wsbgmofo** [comment]
这个我领了 2018062517500.tar.gz
